version: "3"

services:
  webapp-todo:
    container_name: webapp-todo
    build:
      context: ./frontend/webapp-todo
      dockerfile: Dockerfile
    volumes:
      - "/app/node_modules"
      - "./frontend/webapp-todo:/app/"
    ports:
      - "3000:3000"
      - "9009:9009"
    restart: on-failure
    environment:
      - NODE_ENV=development
    stdin_open: true
  api-todo:
    container_name: api-todo
    build:
      context: ./services/api-todo
      dockerfile: Dockerfile
    volumes:
      - "/app/node_modules"
      - "./services/api-todo:/app/"
    ports:
      - "3001:3001"
    depends_on:
      - db-todo
    restart: on-failure
    environment:
      NODE_ENV: "development"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "db-todo"
      POSTGRES_HOST: "db-todo"
  db-todo:
    image: postgres:latest
    container_name: db-todo
    volumes:
      - "/database/db-data:/postgres/data"
      - "/database/postgresql.conf:/etc/postgresql/postgresql.conf"
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "db-todo"
      PGDATA: /postgres/data
  pg-admin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    ports:
      - "54105:80"
    restart: on-failure
    volumes:
      - /database/pgadmin:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "facundo.palombo@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    depends_on:
      - db-todo
